services:

  llm-model:
    image: llm-model
    build:
      context: gguf_model
      dockerfile: Dockerfile
    ports:
      - 8007:8007
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  discord-bot-service:
    image: discord-bot-service
    build:
      context: discord_bot_service
      dockerfile: Dockerfile
    network_mode: host
    env_file:
      - discord_bot_service/.env