[tool.ruff]
lint.select = [
    "E", # pycodestyle errors
    "W", # pycodestyle warnings
    "F", # pyflakes
    "C", # flake8-comprehensions
    "B", # flake8-bugbear
    # "I",
    "SIM",
    "UP",
]

line-length = 100

lint.ignore = [
    "E501", # line too long, handled by format
    "B008", # do not perform function calls in argument defaults
    "I",
    "C408"
    # "F401",
]

fix = false
show-fixes = true
